In [3]:
# Load & Inspect Data

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("City_of_Edmonton_-_Neighbourhoods_20261008.csv")

In [6]:
# check the dataframe loaded
df.head(2)

,Neighbourhood Name,Neighbourhood Number,Descriptive Name,Description,Effective Start Date,Effective End Date,Civic Ward,Planning District,Geometry Multipolygon
0,ABBOTTSFIELD,2010,Abbottsfield,"Abbottsfield was once owned by E.F. Carey, one...",1981-10-01,NaN,Métis,North Central,MULTIPOLYGON (((-113.38763361949056 53.5761348...
1,ALBANY,3460,Albany,NaN,2011-06-13,NaN,Anirniq,Northwest,MULTIPOLYGON (((-113.56024507936962 53.6316036...

In [7]:
df.shape

(407, 9)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 407 entries, 0 to 406
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Neighbourhood Name     407 non-null    str
 1   Neighbourhood Number   407 non-null    int64
 2   Descriptive Name       407 non-null    str
 3   Description            340 non-null    str
 4   Effective Start Date   407 non-null    str
 5   Effective End Date     0 non-null      float64
 6   Civic Ward             407 non-null    str
 7   Planning District      407 non-null    str
 8   Geometry Multipolygon  407 non-null    str
dtypes: float64(1), int64(1), str(7)
memory usage: 17.6 KB

In [9]:
df.describe()

       Neighbourhood Number  Effective End Date
count            407.000000                 0.0
mean            4453.285012                 NaN
std             1659.820471                 NaN
min             1010.000000                 NaN
25%             3195.000000                 NaN
50%             4486.000000                 NaN
75%             5576.000000                 NaN
max             8889.000000                 NaN

In [10]:
# how many NA values?
df.isna().sum()

Neighbourhood Name         0
Neighbourhood Number       0
Descriptive Name           0
Description               67
Effective Start Date       0
Effective End Date       407
Civic Ward                 0
Planning District          0
Geometry Multipolygon      0
dtype: int64

In [11]:
df["Description"].isna().sum()

np.int64(67)

In [13]:
# let's get rid of rows with missing data
new = df.dropna()

In [14]:
new.head()

Empty DataFrame
Columns: [Neighbourhood Name, Neighbourhood Number, Descriptive Name, Description, Effective Start Date, Effective End Date, Civic Ward, Planning District, Geometry Multipolygon]
Index: []

In [15]:
new.shape

(0, 9)

In [16]:
# fill in the missing values with "Unknown"
df["Description"] = df["Description"].fillna("Unknown")

In [17]:
df.head(2)

,Neighbourhood Name,Neighbourhood Number,Descriptive Name,Description,Effective Start Date,Effective End Date,Civic Ward,Planning District,Geometry Multipolygon
0,ABBOTTSFIELD,2010,Abbottsfield,"Abbottsfield was once owned by E.F. Carey, one...",1981-10-01,NaN,Métis,North Central,MULTIPOLYGON (((-113.38763361949056 53.5761348...
1,ALBANY,3460,Albany,Unknown,2011-06-13,NaN,Anirniq,Northwest,MULTIPOLYGON (((-113.56024507936962 53.6316036...

In [18]:
# rename the date fields
df = df.rename(columns = {'Effective Start Date': 'start_date', 'Effective End Date': 'end_date'})

In [19]:
# check that the columns renamed successfully
df.info(2)

<class 'pandas.DataFrame'>
RangeIndex: 407 entries, 0 to 406
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Neighbourhood Name     407 non-null    str
 1   Neighbourhood Number   407 non-null    int64
 2   Descriptive Name       407 non-null    str
 3   Description            407 non-null    str
 4   start_date             407 non-null    str
 5   end_date               0 non-null      float64
 6   Civic Ward             407 non-null    str
 7   Planning District      407 non-null    str
 8   Geometry Multipolygon  407 non-null    str
dtypes: float64(1), int64(1), str(7)
memory usage: 17.6 KB

In [20]:
# fill in the missing end dates with something silly
# we are going to change the end date for ALL neighbourhoods to be whatever the latest date in start_date is
df["end_date"] = df["end_date"].fillna(df["start_date"].max())

In [21]:
df.head(2)

,Neighbourhood Name,Neighbourhood Number,Descriptive Name,Description,start_date,end_date,Civic Ward,Planning District,Geometry Multipolygon
0,ABBOTTSFIELD,2010,Abbottsfield,"Abbottsfield was once owned by E.F. Carey, one...",1981-10-01,2026-01-15,Métis,North Central,MULTIPOLYGON (((-113.38763361949056 53.5761348...
1,ALBANY,3460,Albany,Unknown,2011-06-13,2026-01-15,Anirniq,Northwest,MULTIPOLYGON (((-113.56024507936962 53.6316036...

In [22]:
# let's check for any duplicate rows
df.duplicated().sum()

np.int64(0)

In [23]:
# let's say that duplicates are defined by the value in the "Description" field. Now do we have duplicates?
df.duplicated(subset = ["Description"]).sum()

np.int64(158)

In [24]:
# let's get rid of those duplicates
no_dupes = df.drop_duplicates(subset = ["Description"])

In [25]:
no_dupes.shape

(249, 9)

In [26]:
df["Civic Ward"].unique()

<StringArray>
[                'Métis',               'Anirniq',           'Nakota Isga',
            'Sspomitapi', 'Ipiihkoohkanipiaohtsi',              'papastew',
             'pihêsiwin',                  'Dene',        'tastawiyiniwak',
         'sipiwiyiniwak',             'O-day'min',               'Karhiio']
Length: 12, dtype: str

In [27]:
# how many neighbourhoods belong to each ward?
df["Civic Ward"].value_counts()

Civic Ward
Nakota Isga              54
Métis                    47
Anirniq                  41
papastew                 38
sipiwiyiniwak            38
Dene                     35
Karhiio                  33
Ipiihkoohkanipiaohtsi    31
pihêsiwin                29
Sspomitapi               24
tastawiyiniwak           23
O-day'min                14
Name: count, dtype: int64

In [28]:
# what proportion of neighbourhoods belong to each ward?
df["Civic Ward"].value_counts(normalize = True)

Civic Ward
Nakota Isga              0.132678
Métis                    0.115479
Anirniq                  0.100737
papastew                 0.093366
sipiwiyiniwak            0.093366
Dene                     0.085995
Karhiio                  0.081081
Ipiihkoohkanipiaohtsi    0.076167
pihêsiwin                0.071253
Sspomitapi               0.058968
tastawiyiniwak           0.056511
O-day'min                0.034398
Name: proportion, dtype: float64

In [29]:
# selecting & filtering data
# if I only want to see one column
df["Description"]

0      Abbottsfield was once owned by E.F. Carey, one...
1                                                Unknown
2      One of the city's older residential neighbourh...
3      This non-residential neighbourhood is largely ...
4                                Formerly Decoteau North
                             ...
402    Wîhkwêntôwin is a Cree word that can be transl...
403    This non-residential neighbourhood is limited ...
404    This non-residential neighbourhood is limited ...
405    York is somewhat of a 'pioneer' neighbourhood....
406    Mostly Industrial, River Valley Parkland or co...
Name: Description, Length: 407, dtype: str

In [30]:
df["Description"].head(10)

0    Abbottsfield was once owned by E.F. Carey, one...
1                                              Unknown
2    One of the city's older residential neighbourh...
3    This non-residential neighbourhood is largely ...
4                              Formerly Decoteau North
5    Planned in the 1970s, this area's multi-family...
6                                              Unknown
7    Once farmed by the Allen family, this area was...
8    The name Ambleside most likely originates from...
9    This non-residential neighbourhood forms part ...
Name: Description, dtype: str

In [31]:
df[["Neighbourhood Name", "Neighbourhood Number"]]

           Neighbourhood Name  Neighbourhood Number
0                ABBOTTSFIELD                  2010
1                      ALBANY                  3460
2              ALBERTA AVENUE                  1010
3     ALBERTA PARK INDUSTRIAL                  4010
4                       ALCES                  6669
..                        ...                   ...
402              WÎHKWÊNTÔWIN                  1151
403  YELLOWHEAD CORRIDOR EAST                  1270
404  YELLOWHEAD CORRIDOR WEST                  1280
405                      YORK                  2720
406     YOUNGSTOWN INDUSTRIAL                  4660

[407 rows x 2 columns]

In [32]:
# filtering
# I want to see only neighbourhoods whose ID is > 6000
df[df["Neighbourhood Number"] > 6000].shape

(93, 9)

In [33]:
# I want to see only neighbourhoods whose name is more than 10 characters long
df[df["Neighbourhood Name"].str.len() > 10].shape

(224, 9)

In [34]:
# now I want to see only neighbourhoods where BOTH conditions are true
df[(df["Neighbourhood Number"] > 6000) & (df["Neighbourhood Name"].str.len() > 10)].shape

(49, 9)

In [35]:
new_neighbourhoods = df[df["Neighbourhood Number"] > 6000]

In [36]:
new_neighbourhoods.head(2)

,Neighbourhood Name,Neighbourhood Number,Descriptive Name,Description,start_date,end_date,Civic Ward,Planning District,Geometry Multipolygon
4,ALCES,6669,Alces,Formerly Decoteau North,2019-07-25,2026-01-15,Sspomitapi,Ellerslie,MULTIPOLYGON (((-113.37648878753762 53.4248774...
20,ANTHONY HENDAY SOUTH EAST,6665,Anthony Henday South East,This non-residential neighbourhood forms part ...,2006-07-19,2026-01-15,Sspomitapi,Ellerslie,MULTIPOLYGON (((-113.34460360980685 53.4415737...

In [37]:
# let's create a new column
df["isNew"] = df["Neighbourhood Number"] > 6000

In [38]:
df.head(2)

,Neighbourhood Name,Neighbourhood Number,Descriptive Name,Description,start_date,end_date,Civic Ward,Planning District,Geometry Multipolygon,isNew
0,ABBOTTSFIELD,2010,Abbottsfield,"Abbottsfield was once owned by E.F. Carey, one...",1981-10-01,2026-01-15,Métis,North Central,MULTIPOLYGON (((-113.38763361949056 53.5761348...,False
1,ALBANY,3460,Albany,Unknown,2011-06-13,2026-01-15,Anirniq,Northwest,MULTIPOLYGON (((-113.56024507936962 53.6316036...,False

In [39]:
# fix our data types for the date columns
df["start_date"] = pd.to_datetime(df["start_date"])

In [40]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 407 entries, 0 to 406
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Neighbourhood Name     407 non-null    str
 1   Neighbourhood Number   407 non-null    int64
 2   Descriptive Name       407 non-null    str
 3   Description            407 non-null    str
 4   start_date             407 non-null    datetime64[us]
 5   end_date               407 non-null    object
 6   Civic Ward             407 non-null    str
 7   Planning District      407 non-null    str
 8   Geometry Multipolygon  407 non-null    str
 9   isNew                  407 non-null    bool
dtypes: bool(1), datetime64[us](1), int64(1), object(1), str(6)
memory usage: 18.0+ KB

In [41]:
# let's add another new column with the year the neighbourhood was created
df["start_year"] = df["start_date"].dt.year

In [42]:
df.head(2)

,Neighbourhood Name,Neighbourhood Number,Descriptive Name,Description,start_date,end_date,Civic Ward,Planning District,Geometry Multipolygon,isNew,start_year
0,ABBOTTSFIELD,2010,Abbottsfield,"Abbottsfield was once owned by E.F. Carey, one...",1981-10-01,2026-01-15,Métis,North Central,MULTIPOLYGON (((-113.38763361949056 53.5761348...,False,1981
1,ALBANY,3460,Albany,Unknown,2011-06-13,2026-01-15,Anirniq,Northwest,MULTIPOLYGON (((-113.56024507936962 53.6316036...,False,2011

In [43]:
# Merge & Reshaping

# Assumptions
- Neighbourhoods do not have end dates as they all still exist.
- End date is included for the possibility of a neighbourhood no longer being active.

In [44]:
pdf = pd.read_csv("Pet__Licenses_by_Neighbourhood_20261008.csv")

In [47]:
pdf.info()

<class 'pandas.DataFrame'>
RangeIndex: 84469 entries, 0 to 84468
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   YEAR                84469 non-null  int64
 1   MONTH               84469 non-null  str
 2   MONTH_NUMBER        84469 non-null  int64
 3   LICENSE_DATE        84469 non-null  str
 4   NEIGHBOURHOOD       84457 non-null  str
 5   NEIGHBOURHOOD_ID    84457 non-null  str
 6   PET_TYPE            84467 non-null  str
 7   BREED               84232 non-null  str
 8   GENDER              84335 non-null  str
 9   SPAYED_OR_NEUTERED  84469 non-null  str
 10  LATITUDE            84406 non-null  float64
 11  LONGITUDE           84406 non-null  float64
 12  LOCATION            84406 non-null  str
 13  COUNT               84469 non-null  int64
 14  Point Location      84406 non-null  str
dtypes: float64(2), int64(3), str(10)
memory usage: 6.4 MB

In [50]:
## some pets have multiple neighbourhoods, this prevents us from converting the data type as is
pdf["NEIGHBOURHOOD_ID"] = pdf["NEIGHBOURHOOD_ID"].str.split(",").str[0]
pdf

,YEAR,MONTH,MONTH_NUMBER,LICENSE_DATE,NEIGHBOURHOOD,NEIGHBOURHOOD_ID,PET_TYPE,BREED,GENDER,SPAYED_OR_NEUTERED,LATITUDE,LONGITUDE,LOCATION,COUNT,Point Location
0,2026,July,7,July 2026,"Marquis, Evergreen",2671,Dog,NOVA SCOTIA DUCK TOLLING RETRIEVER,Female,Yes,NaN,NaN,NaN,1,NaN
1,2025,November,11,November 2025,Greenview,6280,Cat,DOMESTIC (MEDIUM HAIR),Male,Yes,53.475394,-113.427810,"(53.47539385786576, -113.42780973626564)",1,POINT (-113.42780973626564 53.47539385786576)
2,2026,July,7,July 2026,Baranow,3020,Cat,DOMESTIC (SHORT HAIR),Male,Yes,53.605145,-113.535873,"(53.60514463104835, -113.53587266453894)",1,POINT (-113.53587266453894 53.60514463104835)
3,2025,January,1,January 2025,Summerside,6213,Cat,DOMESTIC (SHORT HAIR),Male,Yes,53.417528,-113.461227,"(53.4175276127026, -113.46122737605207)",1,POINT (-113.46122737605207 53.4175276127026)
4,2026,June,6,June 2026,The Uplands,4464,Cat,DOMESTIC (SHORT HAIR),Male,Yes,53.461707,-113.657391,"(53.461707245994, -113.65739134608921)",1,POINT (-113.65739134608921 53.461707245994)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84464,2026,May,5,May 2026,Oleskiw,4360,Cat,DOMESTIC (SHORT HAIR),Male,Yes,53.497340,-113.608766,"(53.49733975842764, -113.60876578846745)",1,POINT (-113.60876578846745 53.49733975842764)
84465,2025,November,11,November 2025,Weinlos,6770,Dog,BERNESE MOUNTAIN DOG,Male,Yes,53.459907,-113.413836,"(53.459906787317394, -113.4138360275789)",1,POINT (-113.4138360275789 53.459906787317394)
84466,2026,April,4,April 2026,York,2720,Cat,DOMESTIC (SHORT HAIR),Male,Yes,53.602843,-113.430212,"(53.60284342250439, -113.4302123105938)",1,POINT (-113.4302123105938 53.60284342250439)
84467,2026,July,7,July 2026,Balwin,2020,Cat,DOMESTIC (SHORT HAIR),Male,Yes,53.587951,-113.455075,"(53.58795101014664, -113.455075346126)",1,POINT (-113.455075346126 53.58795101014664)
84468,2026,March,3,March 2026,Beacon Heights,2040,Dog,SIBERIAN HUSKY,Female,Yes,53.573539,-113.406040,"(53.57353937729379, -113.40604010217766)",1,POINT (-113.40604010217766 53.57353937729379)

In [53]:
pdf["NEIGHBOURHOOD_ID"] = pd.to_numeric(pdf["NEIGHBOURHOOD_ID"])
pdf.info()

<class 'pandas.DataFrame'>
RangeIndex: 84469 entries, 0 to 84468
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   YEAR                84469 non-null  int64
 1   MONTH               84469 non-null  str
 2   MONTH_NUMBER        84469 non-null  int64
 3   LICENSE_DATE        84469 non-null  str
 4   NEIGHBOURHOOD       84457 non-null  str
 5   NEIGHBOURHOOD_ID    84457 non-null  float64
 6   PET_TYPE            84467 non-null  str
 7   BREED               84232 non-null  str
 8   GENDER              84335 non-null  str
 9   SPAYED_OR_NEUTERED  84469 non-null  str
 10  LATITUDE            84406 non-null  float64
 11  LONGITUDE           84406 non-null  float64
 12  LOCATION            84406 non-null  str
 13  COUNT               84469 non-null  int64
 14  Point Location      84406 non-null  str
dtypes: float64(3), int64(3), str(9)
memory usage: 6.8 MB

In [55]:
# Merging datasets

In [57]:
# need to make sure the merged columns have the same name
pdf = pdf.rename(columns = {'NEIGHBOURHOOD_ID': 'Neighbourhood Number', 'NEIGHBOURHOOD': 'Neighbourhood Name'})

In [69]:
merged = df.merge(pdf, on="Neighbourhood Number")

In [70]:
merged.info()

<class 'pandas.DataFrame'>
RangeIndex: 84455 entries, 0 to 84454
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Neighbourhood Name_x   84455 non-null  str
 1   Neighbourhood Number   84455 non-null  int64
 2   Descriptive Name       84455 non-null  str
 3   Description            84455 non-null  str
 4   start_date             84455 non-null  datetime64[us]
 5   end_date               84455 non-null  object
 6   Civic Ward             84455 non-null  str
 7   Planning District      84455 non-null  str
 8   Geometry Multipolygon  84455 non-null  str
 9   isNew                  84455 non-null  bool
 10  start_year             84455 non-null  int32
 11  YEAR                   84455 non-null  int64
 12  MONTH                  84455 non-null  str
 13  MONTH_NUMBER           84455 non-null  int64
 14  LICENSE_DATE           84455 non-null  str
 15  Neighbourhood Name_y   84455 non-null  str
 16  PET_TYPE               84453 non-null  str
 17  BREED                  84218 non-null  str
 18  GENDER                 84321 non-null  str
 19  SPAYED_OR_NEUTERED     84455 non-null  str
 20  LATITUDE               84406 non-null  float64
 21  LONGITUDE              84406 non-null  float64
 22  LOCATION               84406 non-null  str
 23  COUNT                  84455 non-null  int64
 24  Point Location         84406 non-null  str
dtypes: bool(1), datetime64[us](1), float64(2), int32(1), int64(4), object(1), str(15)
memory usage: 10.1+ MB

In [71]:
df["Neighbourhood Number"].nunique()

407

In [72]:
pdf["Neighbourhood Number"].nunique()

333

In [68]:
merged["Neighbourhood Number"].nunique()

332

In [73]:
validate_merge = merged = df.merge(pdf, on="Neighbourhood Number", how="left", indicator=True)

In [74]:
validate_merge.head(2)

,Neighbourhood Name_x,Neighbourhood Number,Descriptive Name,Description,start_date,end_date,Civic Ward,Planning District,Geometry Multipolygon,isNew,...,PET_TYPE,BREED,GENDER,SPAYED_OR_NEUTERED,LATITUDE,LONGITUDE,LOCATION,COUNT,Point Location,_merge
0,ABBOTTSFIELD,2010,Abbottsfield,"Abbottsfield was once owned by E.F. Carey, one...",1981-10-01,2026-01-15,Métis,North Central,MULTIPOLYGON (((-113.38763361949056 53.5761348...,False,...,Cat,DOMESTIC (MEDIUM HAIR),Male,Yes,53.574143,-113.388758,"(53.57414343327946, -113.38875800528291)",1.0,POINT (-113.38875800528291 53.57414343327946),both
1,ABBOTTSFIELD,2010,Abbottsfield,"Abbottsfield was once owned by E.F. Carey, one...",1981-10-01,2026-01-15,Métis,North Central,MULTIPOLYGON (((-113.38763361949056 53.5761348...,False,...,Dog,LABRADOR RETRIEVER,Female,Yes,53.574143,-113.388758,"(53.57414343327946, -113.38875800528291)",1.0,POINT (-113.38875800528291 53.57414343327946),both

In [75]:
validate_merge["_merge"].value_counts()

_merge
both          84455
left_only        75
right_only        0
Name: count, dtype: int64

In [81]:
merged.groupby("Neighbourhood Name_x").agg({"COUNT": ["sum", "mean"]})
# mean is not meaningful, as all counts are 1

                           COUNT
                             sum mean
Neighbourhood Name_x
ABBOTTSFIELD                87.0  1.0
ALBANY                      89.0  1.0
ALBERTA AVENUE             756.0  1.0
ALBERTA PARK INDUSTRIAL      0.0  NaN
ALCES                       28.0  1.0
...                          ...  ...
WÎHKWÊNTÔWIN              1219.0  1.0
YELLOWHEAD CORRIDOR EAST     4.0  1.0
YELLOWHEAD CORRIDOR WEST     0.0  NaN
YORK                       349.0  1.0
YOUNGSTOWN INDUSTRIAL        1.0  1.0

[407 rows x 2 columns]